### ISSUE TITLE
Action fails if all output formats are specified in a non .tmp folder

### ISSUE THREAD

**Issue by ikenna** [swimmwatch/openapi-diff-action#1]
## Expected Behavior
When I specify all the output formats with my specified filenames, they should be created. 

## Current Behavior
The action fails with:  
> Run sudo chown -R $USER:$USER .tmp
>   sudo chown -R $USER:$USER .tmp
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>   env:
>     run_number: ${GITHUB_RUN_NUMBER}
> chown: cannot access '.tmp': No such file or directory
> Error: Process completed with exit code 1.

## Possible Solution
The step "Post: Change folder own group" which does run 'sudo chown -R $USER:$USER .tmp' should only occur if .tmp exists. Or if it does occur, ignore the error. 

## Steps to Reproduce
Link to live example build https://github.com/ikenna/acme-pet-supplies/runs/7460315228?check_suite_focus=true 
1. Run the action, specifying all the available output formats in custom filenames. E.g

>       - name: "Run breaking change check (with OpenAPITools/openapi-diff)"
>         id: diff_state
>         uses: swimmwatch/openapi-diff-action@v1.0.0
>         with:
>           old-spec: base/reference/product-catalog-api.oas.yaml
>           new-spec: head/reference/product-catalog-api.oas.yaml
>           json: "diff.json"
>           markdown: "diff.md"
>           text: "diff.txt"

## Context (Environment)
1. Failing build with all the formats specified in a non .tmp path  : https://github.com/ikenna/acme-pet-supplies/runs/7460315228?check_suite_focus=true 

2. Passing build with only three formats specified in a non .tmp path  : https://github.com/ikenna/acme-pet-supplies/runs/7460555288?check_suite_focus=true
 

## Detailed Description
I can't successfully run the action if I specify custom names for all the output formats. But I can if I specify a subset. 

## Possible Implementation
Ignore the error if .tmp does not exist.
>  run: sudo chown -R $USER:$USER .tmp  2>/dev/null

**Comment by swimmwatch** [comment]
Hi, @ikenna! Thank you for this bug report. I have fixed in PR #2. Сhanges will take effect in v1.0.1.

**Comment by ikenna** [comment]
Thank you @swimmwatch!
